AllCops:
  Exclude:
    - 'test/dummy/script/**/*'
    - 'vendor/bundle/**/*'

Metrics/AbcSize:
  Max: 22.11 # TODO: Lower to 15
  Exclude:
    - 'test/**/*'

Metrics/ClassLength:
  Exclude:
    - 'test/**/*'

Metrics/CyclomaticComplexity:
  Max: 10 # TODO: Lower to 6

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Max: 22
  Exclude:
    - 'test/**/*'

Metrics/ParameterLists:
  Max: 13

Metrics/PerceivedComplexity:
  Max: 9 # TODO: Lower to 7

Rails:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/SpaceAroundOperators:
  AllowForAlignment: true
